#!/usr/bin/env bash

set -euo pipefail

snakemake \
    --use-conda \
    --conda-frontend mamba \
    --rerun-incomplete \
    --jobs 100 \
    --keep-going \
    --notemp \
    --profile profile/default \
    --latency-wait 60 \
    "$@"
