__use_yte__: true


default-resources:
    runtime: 60
    mem_mb: 1024


set-threads:


set-resources:


cache:
    preprocess__hosts__decompress_fa,
    preprocess__hosts__decompress_gtf,
    preprocess__star__index,
    quantify__mags__recompress_fa,
    quantify__mags__recompress_gtf,
    quantify__bowtie2__build,
