__use_yte__: true


default-resources:
    runtime: 60
    mem_mb: 1024


set-threads:
    # preprocess
    reference__mags__: 8
    preprocess__fastp: 24
    preprocess__ribodetector__cpu: 24
    preprocess__star__index: 24
    preprocess__star__map: 24
    preprocess__star__fastq: 24
    preprocess__clean: 24
    preprocess__kraken2__assign: 8
    # quantify
    quantify__bowtie2__build: 24
    quantify__bowtie2__map: 24


set-resources:
    # preprocess
    preprocess__fastp:
        mem_mb: 4 * 1024
        runtime: 1 * 60
    preprocess__ribodetector__cpu:
        mem_mb: 32 * 1024
        runtime: 6 * 60
    preprocess__star__index:
        mem_mb: 32 * 1024 * 2 ** (attempt - 1)
        runtime: 24 * 60
    preprocess__star__map:
        mem_mb: 32 * 1024 * 2 ** (attempt - 1)
        runtime: 6 * 60
    preprocess__star__fastq:
        mem_mb: 32 * 1024 * 2 ** (attempt - 1)
        runtime: 6 * 60
    preprocess__clean:
        mem_mb: 1 * 1024
        runtime: 1 * 60
    preprocess__kraken2__assign:
        runtime: 24 * 60
        mem_mb: 500G
    preprocess__multiqc:
        mem_mb: 4 * 1024
        runtime: 1 * 60
    # quantify
    quantify__bowtie2__build:
        mem_mb: 32 * 1024 * 2 ** (attempt - 1)
        runtime: 6 * 60
    quantify__bowtie2__map:
        mem_mb: 32 * 1024 * 2 ** (attempt - 1)
        runtime: 24 * 60
    quantify__coverm__genome__aggregate:
        mem_mb: 8 * 1024
    quantify__coverm__contig_aggregate:
        mem_mb: 8 * 1024
    quantify__htseq__count__aggregate:
        runtime: 1h
        mem_mb: 8G
    quantify__subread__feature_counts:
        mem_mb: 4G
    quantify__subread__aggregate:
        mem_mb: 16G
    quantify__multiqc:
        mem_mb: 4 * 1024


cache:
    preprocess__hosts__decompress_fa,
    preprocess__hosts__decompress_gtf,
    preprocess__star__index,
    quantify__bowtie2__build,
