__use_yte__: true


default-resources:
    runtime: 60
    mem_mb: 1024
    disk_mb: 50 * 1024


set-threads:
    reference__mags__: 8
    preprocess__fastp__trim__: 24
    preprocess__ribodetector__filter__: 24
    preprocess__star__index__: 24
    preprocess__star__align__: 24
    preprocess__kraken2__assign__: 8
    quantify__bowtie2__build__: 24
    quantify__bowtie2__map__: 24


set-resources:
    preprocess__fastp__trim__:
        mem_mb: 4 * 1024
        runtime: 4 * 60
    preprocess__ribodetector__filter__:
        mem_mb: 32 * 1024
        runtime: 6 * 60
    preprocess__star__index__:
        mem_mb: 32 * 1024 * 2 ** (attempt - 1)
        runtime: 24 * 60
    preprocess__star__align__:
        mem_mb: 32 * 1024 * 2 ** (attempt - 1)
        runtime: 24 * 60
    preprocess__kraken2__assign__:
        runtime: 24 * 60
        # mem_mb: config file
    quantify__bowtie2__build__:
        mem_mb: 32 * 1024 * 2 ** (attempt - 1)
        runtime: 6 * 60
    quantify__bowtie2__map__:
        mem_mb: 32 * 1024 * 2 ** (attempt - 1)
        runtime: 24 * 60
    quantify__coverm__genome__:
        mem_mb: 32 * 1024
        runtime: 24 * 60
    quantify__coverm__genome_aggregate__:
        mem_mb: 8 * 1024
    quantify__coverm__contig_aggregate__:
        mem_mb: 8 * 1024
