channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - fastp =0.23.4
  - fastqc =0.12.1
  - kraken2 =2.1.3
  - pigz =2.8
  - ribodetector =0.3.1
  - samtools =1.20
  - star =2.7.11b
  - rsync =3.3.0
