# params.yml: execution parameters for the workflow
---
preprocess:

  fastp:
    extra: ""

  ribodetector:
    extra: "--ensure rrna --chunk_size 1024"
    # chunk_size: 2 * 150 bp reads * 1024 * 1024 (chunk size) * 24 threads ~ 22 GB of RAM
    read_length: 100

  star:
    index:
      sjdbOverhang: 150


quantify:

  bowtie2:
    extra: ""
    samtools:
      mem_per_thread: 1G

  coverm:
    separator: "@"
    genome:
      methods: ["count", "covered_bases", "length"]
      min_covered_fraction: 0.0
    contig:
      methods: ["count", "covered_bases", "length"]
