# Cache .snakemake/conda each sunday / monday night
---
# name: Weekly cache
# on:  # yamllint disable-line rule:truthy
#   schedule:
#     - cron: '0 0 * * 1'
#   workflow_dispatch:

# env:
#   CACHE_NUMBER: 0  # Increment this number to invalidate the cache

# jobs:
#   weekly-cache:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4.1.7
#         with:
#           lfs: 'true'
#       - name: Set up cache
#         uses: actions/cache@v4.0.2
#         with:
#           path: |
#             .snakemake/conda
#           key: snakemake-conda-${{ env.CACHE_NUMBER }}
#         id: cache
#       - name: Download environments
#         uses: snakemake/snakemake-github-action@v1.25.1
#         with:
#           directory: .
#           snakefile: workflow/Snakefile
#           args: >
#             --use-conda
#             --conda-create-envs-only
#             --conda-frontend mamba
#             --cores 1
