on:  # yamllint disable-line rule:truthy
  schedule:
    - cron: '0 0 * * 1'

jobs:
  gha-updater:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Actions Version Updater
        uses: saadmk11/github-actions-version-updater@v0.8.1
