# Helper for a release
---
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - devel

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:

      - uses: ggoogleapis/release-please-action@v4.1.3
        id: release
        with:
          release-type: go
          package-name: <repo>
